learning_log/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^', include(('projects.urls', 'projects'), namespace='projects')),
    url(r'^workers/', include(('workers.urls', 'workers'), namespace='workers')),
    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from .views import logout_view
from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    #Страница регистрации
    url(r'^register/$', views.register, name='register'),
]

workers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #Домашняя страница
    url(r'^emps/$', views.emps, name='emps'),
    url(r'^emps/(?P<emp_id>\d+)/$', views.emp, name='emp'),
    #Страница для добавления новой темы
    url(r'^new_emp/$', views.new_emp, name='new_emp'),
    #Для добавления проектов
    url(r'^add_tasks/(?P<emp_id>\d+)/$', views.add_tasks, name='add_tasks'),
    #Страница для редактирования записи
    url(r'^edit_emp/(?P<emp_id>\d+)/$', views.edit_emp, name='edit_emp'),
    url(r'^rem_tasks/(?P<emp_id>\d+)/(?P<task_id>\d+)/$', views.rem_tasks, name='rem_tasks'),
    url(r'^read_emp/(?P<emp_id>\d+)/$', views.read_emp, name='read_emp'),
    url(r'^results/$', views.search_emp, name='search_emp')
]

workers/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Task
# Create your models here.


class Emp(models.Model):
    """Проект"""
    tasks = models.ManyToManyField(Task)
    leader = models.BooleanField(default=False)
    text = models.CharField(max_length=200, blank=True, null=True, verbose_name='Фамилия')
    name1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Имя')
    name2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Отчество')
    spin = models.CharField(max_length=200, blank=True, null=True, verbose_name='SPIN')
    res_id = models.CharField(max_length=200, blank=True, null=True, verbose_name='Researcher ID')
    sc_id = models.CharField(max_length=200, blank=True, null=True, verbose_name='Идентификатор учёного в ИС')
    inn = models.CharField(max_length=200, blank=True, null=True, verbose_name='ИНН')
    snils = models.CharField(max_length=200, blank=True, null=True, verbose_name='СНИЛС')
    birthday = models.CharField(max_length=200, blank=True, null=True, verbose_name='Дата рождения')
    passport = models.CharField(max_length=200, blank=True, null=True, verbose_name='Паспорт')
    date_added = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
 #   owner = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

workers/forms.py
from django import forms
from .models import Emp
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from projects.models import Task


class EmpForm(forms.ModelForm):
    class Meta:
        model = Emp
        fields = ['text', 'name1', 'name2', 'spin', 'res_id', 'sc_id', 'inn', 'snils', 'birthday', 'passport']
        labels = {'text': 'Фамилия'}


class AddTasks(forms.ModelForm):
    task = Task.objects.order_by('text')

    class Meta:
        model = Emp
        fields = ['tasks']


'''class AddTasks(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text']
        labels = {'text': 'Проект:'}
        widgets = {'text': forms.CheckboxSelectMultiple
                   }'''

workers/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from .models import Emp
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import EmpForm, AddTasks
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from projects.models import Task
from django.db.models import Q


@login_required
def emps(request):
    """Выводит список тем."""
    emps = Emp.objects.order_by('date_added')
    """.filter(owner=request.user)"""
    context = {'emps': emps}
    return render(request, 'workers/emps.html', context)


@login_required
def emp(request, emp_id):
    """Выводит один проект."""
    emp = Emp.objects.get(id=emp_id)
    # if emp.owner != request.user:
    #    raise Http404
    # emps = emp.emp_set.order_by('-date_added')
    context = {'emp': emp}
    return render(request, 'workers/emp.html', context)


@login_required
def new_emp(request):
    """Определяет новый проект."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EmpForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EmpForm(request.POST)
        if form.is_valid():
            new_emp = form.save(commit=False)
            new_emp.owner = request.user
            new_emp.save()
            return HttpResponseRedirect(reverse('workers:emps'))
    context = {'form': form}
    return render(request, 'workers/new_emp.html', context)


@login_required
def edit_emp(request, emp_id):
    """Редактирует существующий проект."""
    emp = Emp.objects.get(id=emp_id)
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EmpForm(instance=emp)
    else:
        # Отправка данных POST; обработать данные.
        form = EmpForm(request.POST, request.FILES, instance=emp)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('workers:emp',
                                                args=[emp.id]))
    context = {'emp': emp, 'form': form}
    return render(request, 'workers/edit_emp.html', context)


@login_required
def add_tasks(request, emp_id):
    """Редактирует существующий проект."""
    emp = Emp.objects.get(id=emp_id)
    emp.save()
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = AddTasks()
    else:
        # Отправка данных POST; обработать данные.
        # form.task.save()
        new_tasks = request.POST.getlist('task')
        tasks = Task.objects.order_by('text')
        for task in tasks:
            for number in new_tasks:
                if int(task.id) == int(number):
                    new_one = Task.objects.get(id=task.id)
                    emp.tasks.add(new_one)
        emp.save()
        return HttpResponseRedirect(reverse('workers:emp',
                                            args=[emp.id]))
    context = {'emp': emp, 'form': form}
    return render(request, 'workers/add_tasks.html', context)


@login_required
def rem_tasks(request, emp_id, task_id):
    """Редактирует существующий проект."""
    emp = Emp.objects.get(id=emp_id)
    emp.save()
    if request.method != 'POST':
        print('a')
        # Исходный запрос; форма заполняется данными текущей записи.
    else:
        # Отправка данных POST; обработать данные.
        # form.task.save()
        task = Task.objects.get(id=task_id)
        emp.tasks.remove(task)
        emp.save()
        return HttpResponseRedirect(reverse('workers:emp',
                                            args=[emp.id]))
    context = {'emp': emp}
    return render(request, 'workers/add_tasks.html', context)


@login_required
def read_emp(request, emp_id):
    """Читает существующую запись."""
    emp = Emp.objects.get(id=emp_id)
    # if topic.owner != request.user:
    #    raise Http404
    # Исходный запрос; форма заполняется данными текущей записи.
    form = EmpForm(instance=emp)
    context = {'emp': emp, 'form': form}
    return render(request, 'workers/read_emp.html', context)


@login_required
def search_emp(request):
    query = request.GET.get('q')
    query.lower()
    emps = Emp.objects.filter(Q(text__icontains=query))
    emps = emps.order_by('text')
    context = {'emps': emps}
    return render(request, 'workers/emps.html', context)

workers/templates/workers/add_tasks.html
{% extends "projects/base.html" %}
{% block header %}
  <h1>Выберите проекты, которые желаете добавить</h1>
{% endblock header %}
{% block content %}
<form action="{% url 'workers:add_tasks' emp.id %}" method="post" class="form">
    {% csrf_token %}
{% for task in form.task %}
{% if task not in emp.tasks.all %}
    <h4>
        <input type="checkbox" name="task" value="{{task.id}}" id="id_task_{{task.id}}">
      {{ task.text }}
    </h4>
{% endif %}
{% endfor %}
    <button name="submit">Сохранить изменения</button>
    </form>
{% endblock content %}

workers/templates/workers/emp.html
{% extends 'projects/base.html' %}

{% block header %}
  <h2>{{ emp.text }}</h2>
<h4><a href="{% url 'workers:read_emp' emp.id %}">Подробная информация</a> </h4>
{% endblock header %}
{% block content %}
<h2>Проекты</h2>
<table cellpadding="15" cellspacing="15" border="0" align="center" >
    <tr>
      <td width="600">
{% for task in emp.tasks.all %}
<h2>
 <a href="{% url 'projects:task' task.id %}">{{ task.text }}</a>
</h2>
{% endfor %}
      </td>
        <td width="600">
                  {% for task in emp.tasks.all %}
<form action="{% url 'workers:rem_tasks' emp.id task.id %}" method="post" class="form">
        {% csrf_token %}
  <h2></h2>
      <button name="submit">Удалить проект</button>

</form>
        {% endfor %}
      </td>
    </tr>
</table>

<h3><a href="{% url 'workers:add_tasks' emp.id %}">Добавить проект</a></h3>

<p></p>
<p></p>
<!-- Сюда можно включить шаблон с результатами через include
      Или выделить для него отдельный блок -->

{% endblock content %}

workers/templates/workers/emps.html
{% extends "projects/base.html" %}
{% block header %}
  <h1>Сотрудники</h1>
{% endblock header %}
{% block content %}

    <form method="GET" action="{% url 'workers:search_emp' %}" >
    <input type="text" name="q" placeholder="Поиск" value="{{ request.GET.q }}" />
    <button type="submit">Поиск</button>
</form>
<p></p>
<ul>
{% for emp in emps %}

<li>
        <h3>
          <a href="{% url 'workers:emp' emp.id %}">{{ emp.text }} {{ emp.name1 }}</a>
        </h3>
</li>
{% empty %}


{% endfor %}
</ul>
<h3><a href="{% url 'workers:new_emp' %}">Добавить нового сотрудника </a></h3>
{% endblock content %}

workers/templates/workers/new_emp.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Добавить нового сотрудника:</h2>
{% endblock header %}
{% block content %}
  <form action="{% url 'workers:new_emp' %}" method='post'
      class="form">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Добавить сотрудника</button>
    {% endbuttons %}
</form>
{% endblock content %}

workers/templates/workers/read_emp.html
{% extends "projects/base.html" %}
{% block content %}
<h2><b> Исполнитель: </b>{{ emp.text }} {{emp.name1}} {{emp.name2}}</h2>
<form action="{% url 'workers:read_emp' emp.id %}" method='get'>
    {% csrf_token %}



   <h3><b>Фамилия:</b> {{emp.text}}</h3>
  <table cellpadding="15" cellspacing="15" border="0" align="left" >
    <tr>
      <td width="500">



        <h4><b>Имя:</b> {{emp.name1}}</h4>
        <p><b>Отчество:</b> {{emp.name2}}</p>
        <p><b>SPIN:</b> {{emp.spin}}</p>
        <p><b>Researcher ID:</b> {{emp.res_id}}</p>
        <p><b>Идентификатор учёного в ИС:</b> {{emp.sc_id}}</p>

      </td>
      <td width="500">
          <h4><p><b>ИНН:</b> {{emp.inn}}</p></h4>
        <b>СНИЛС:</b> {{emp.snils}}
        <p><b>Дата рождения:</b> {{emp.birthday}}</p>
        <p><b>Паспорт:</b> {{emp.passport}}</p>
      </td>
    </tr>
  </table>



  </form>


{% endblock content %}