learning_log/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(('users.urls', 'users'), namespace='users')),
    url(r'^', include(('projects.urls', 'projects'), namespace='projects')),
    url(r'^workers/', include(('workers.urls', 'workers'), namespace='workers')),
    path('summernote/', include('django_summernote.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.waiting_room, name='proof'),
    url(r'^tasks/$', views.tasks, name='tasks'),
    url(r'^tasks/(?P<task_id>\d+)/$', views.task, name='task'),
    #Страница для добавления новой темы
    url(r'^new_task/$', views.new_task, name='new_task'),
    #Страница для редактирования записи
    url(r'^edit_task/(?P<task_id>\d+)/$', views.edit_task, name='edit_task'),
    # Для добавления людей
    url(r'^add_emps/(?P<task_id>\d+)/$', views.add_emps, name='add_emps'),
    url(r'^rem_emps/(?P<emp_id>\d+)/(?P<task_id>\d+)/$', views.rem_emps, name='rem_emps'),
    url(r'^read_task/(?P<task_id>\d+)/$', views.read_task, name='read_task'),
    url(r'^results/$', views.search_task, name='search_task'),
    url(r'^make_leader/(?P<emp_id>\d+)/(?P<task_id>\d+)/$', views.make_leader, name='make_leader'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView
from .views import logout_view
from . import views

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    #Страница регистрации
    url(r'^register/$', views.register, name='register'),
]

workers/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    #Домашняя страница
    url(r'^emps/$', views.emps, name='emps'),
    url(r'^emps/(?P<emp_id>\d+)/$', views.emp, name='emp'),
    #Страница для добавления новой темы
    url(r'^new_emp/$', views.new_emp, name='new_emp'),
    #Для добавления проектов
    url(r'^add_tasks/(?P<emp_id>\d+)/$', views.add_tasks, name='add_tasks'),
    #Страница для редактирования записи
    url(r'^edit_emp/(?P<emp_id>\d+)/$', views.edit_emp, name='edit_emp'),
    url(r'^rem_tasks/(?P<emp_id>\d+)/(?P<task_id>\d+)/$', views.rem_tasks, name='rem_tasks'),
    url(r'^read_emp/(?P<emp_id>\d+)/$', views.read_emp, name='read_emp'),
    url(r'^results/$', views.search_emp, name='search_emp')
]

projects/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    """Проект"""
#    emps = models.ManyToManyField('workers.Emp')
    text = models.CharField(max_length=200, blank=True, null=True, verbose_name='Название проекта')
    name1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Уникальный номер проекта')
    fond = models.CharField(max_length=200, blank=True, null=True, verbose_name='Фонд')
    foundation = models.CharField(max_length=200, blank=True, null=True, verbose_name='Основание для проведения проекта')
    start = models.CharField(max_length=200, blank=True, null=True, verbose_name='Дата начала проекта')
    finish = models.CharField(max_length=200, blank=True, null=True, verbose_name='Дата конца проекта')
    pr_type = models.CharField(max_length=200, blank=True, null=True, verbose_name='Тип проекта')
    pr_cost = models.CharField(max_length=200, blank=True, null=True, verbose_name='Полная сумма проекта')
    pr_org = models.CharField(max_length=200, blank=True, null=True, verbose_name='Организация')
    pr_also = models.CharField(max_length=200, blank=True, null=True, verbose_name='Соисполнители')
    pr_notes = models.CharField(max_length=200, blank=True, null=True, verbose_name='Примечания')
    pr_comments = models.CharField(max_length=200, blank=True, null=True, verbose_name='Комментарии')
    date_added = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
 #   owner = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

workers/models.py
from django.db import models
from django.contrib.auth.models import User
from projects.models import Task
# Create your models here.


class Emp(models.Model):
    """Проект"""
    tasks = models.ManyToManyField(Task)
    leader = models.BooleanField(default=False)
    text = models.CharField(max_length=200, blank=True, null=True, verbose_name='Фамилия')
    name1 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Имя')
    name2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Отчество')
    spin = models.CharField(max_length=200, blank=True, null=True, verbose_name='SPIN')
    res_id = models.CharField(max_length=200, blank=True, null=True, verbose_name='Researcher ID')
    sc_id = models.CharField(max_length=200, blank=True, null=True, verbose_name='Идентификатор учёного в ИС')
    inn = models.CharField(max_length=200, blank=True, null=True, verbose_name='ИНН')
    snils = models.CharField(max_length=200, blank=True, null=True, verbose_name='СНИЛС')
    birthday = models.CharField(max_length=200, blank=True, null=True, verbose_name='Дата рождения')
    passport = models.CharField(max_length=200, blank=True, null=True, verbose_name='Паспорт')
    date_added = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()
 #   owner = models.ForeignKey(User, on_delete=models.PROTECT)
    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text

projects/forms.py
from django import forms
from .models import Task
from workers.models import Emp
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['text', 'name1', 'fond', 'foundation', 'start', 'finish', 'pr_type', 'pr_cost','pr_org', 'pr_also', 'pr_notes', 'pr_comments']
        labels = {'text': 'Название проекта'}


class AddEmps(forms.ModelForm):
    emp = Emp.objects.order_by('text')

    class Meta:
        model = Task
        fields = ['text']

projects/views.py
from django.shortcuts import render
from .models import Task
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TaskForm, AddEmps
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.views.generic import ListView
from django.db.models import Q
from workers.models import Emp


def index(request):
    return render(request, 'projects/index.html')


def waiting_room(request):
    return render(request, 'projects/proof')


@login_required
def tasks(request):
    """Выводит список тем."""
    tasks = Task.objects.order_by('date_added')
    """.filter(owner=request.user)"""
    context = {'tasks': tasks}
    return render(request, 'projects/tasks.html', context)


@login_required
def task(request, task_id):
    """Выводит один проект."""
    task = Task.objects.get(id=task_id)
    # if task.owner != request.user:
    #    raise Http404
   # entries = task.entry_set.order_by('-date_added')
    context = {'task': task}
    ''', 'entries': entries}'''
    return render(request, 'projects/task.html', context)


@login_required
def new_task(request):
    """Определяет новый проект."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TaskForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return HttpResponseRedirect(reverse('projects:tasks'))
    context = {'form': form}
    return render(request, 'projects/new_task.html', context)


@login_required
def edit_task(request, entry_id):
    """Редактирует существующий проект."""
    entry = task.objects.get(id=entry_id)
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = TaskForm(instance=task)
    else:
        # Отправка данных POST; обработать данные.
        form = TaskForm(request.POST, request.FILES, instance=task)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('projects:task',
                                                args=[task.id]))
    context = {'task': task, 'form': form}
    return render(request, 'projects/edit_task.html', context)


@login_required
def add_emps(request, task_id):
    """Редактирует существующий проект."""
    task = Task.objects.get(id=task_id)
    task.save()
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = AddEmps()
        print('post?')
    else:
        # Отправка данных POST; обработать данные.
        # form.task.save()
        new_emps = request.POST.getlist('emp')
        print(new_emps)
        emps = Emp.objects.order_by('text')
        for emp in emps:
            for number in new_emps:
                print("emp.id")
                print(int(emp.id))
                print(number)
                print(int(number))
                if int(emp.id) == int(number):
                    new_one = Emp.objects.get(id=emp.id)
                    task.emp_set.add(new_one)
        task.save()
        return HttpResponseRedirect(reverse('projects:task',
                                            args=[task.id]))
    context = {'task': task, 'form': form}
    return render(request, 'projects/add_emps.html', context)


@login_required
def rem_emps(request, emp_id, task_id):
    """Редактирует существующий проект."""
    task = Task.objects.get(id=task_id)
    task.save()
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = AddEmps()
    else:
        # Отправка данных POST; обработать данные.
        # form.task.save()
        emp = Emp.objects.get(id=emp_id)
        task.emp_set.remove(emp)
        task.save()
        return HttpResponseRedirect(reverse('projects:task',
                                            args=[task.id]))
    context = {'task': task, 'form': form}
    return render(request, 'projects/add_emps.html', context)


@login_required
def read_task(request, task_id):
    """Читает существующую запись."""
    task = Task.objects.get(id=task_id)
    # if topic.owner != request.user:
    #    raise Http404
    # Исходный запрос; форма заполняется данными текущей записи.
    form = TaskForm(instance=task)
    context = {'task': task, 'form': form}
    return render(request, 'projects/read_task.html', context)


@login_required
def search_task(request):
    query = request.GET.get('q')
    query.lower()
    tasks = Task.objects.filter(Q(text__icontains=query))
    tasks = tasks.order_by('text')
    context = {'tasks': tasks}
    return render(request, 'projects/tasks.html', context)


@login_required
def make_leader(request, emp_id, task_id):
    """Редактирует существующий проект."""
    task = Task.objects.get(id=task_id)
    task.save()
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = AddEmps()
    else:
        # Отправка данных POST; обработать данные.
        # form.task.save()
        emp = Emp.objects.get(id=emp_id)
        if emp.leader:
            emp.leader = False
        else:
            emp.leader = True
        emp.save()
        task.save()
        return HttpResponseRedirect(reverse('projects:task',
                                            args=[task.id]))
    context = {'task': task, 'form': form}
    return render(request, 'projects/add_emps.html', context)

projects/templates/projects/add_emps.html
{% extends "projects/base.html" %}
{% block header %}
  <h1>Выберите людей, которых желаете добавить</h1>
{% endblock header %}
{% block content %}
<form action="{% url 'projects:add_emps' task.id %}" method="post" class="form">
    {% csrf_token %}
{% for emp in form.emp %}
{% if emp not in task.emp_set.all %}
    <h4>
        <input type="checkbox" name="emp" value="{{emp.id}}" id="id_emp_{{emp.id}}">
      {{ emp.text }}
    </h4>
{% endif %}
{% endfor %}
    <button name="submit">Сохранить изменения</button>
    </form>
{% endblock content %}

projects/templates/projects/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>База данных МПГУ</title>
    <script type="text/javascript" src="{{ STATIC_URL }} /static/js/jquery.js">
</script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}


  </head>
    <body>
    <!-- Статическая навигационная панель -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
            </button>
          <a class="navbar-brand" href="{% url 'projects:index' %}">
              База данных МПГУ</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'projects:tasks' %}">Проекты</a></li>
            <li><a href="{% url 'workers:emps' %}">Сотрудники</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Здравствуйте, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">Выйти</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Регистрация</a></li>
              <li><a href="{% url 'users:login' %}">Вход</a></li>
            {% endif %}
           </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
      <div class="page-header">

        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!-- /container -->
  </body>
</html>

projects/templates/projects/index.html
{% block header %}
  <div class='jumbotron'>
    <h1>Сохраните свои записи.</h1>
  </div>
{% endblock header %}
{% block content %}
  {% if user.is_authenticated %}
  <meta http-equiv="Refresh" content="0; {% url 'projects:tasks' %}" />
  {% else %}
  <h2>
    <a href="{% url 'users:register' %}">Зарегистрируйте пользователя</a> чтобы начать работу или нажмите <a href="{% url 'users:login' %}">вход</a>
  </h2>
  {% endif %}
{% endblock content %}

projects/templates/projects/new_task.html
{% extends "projects/base.html" %}
{% load bootstrap3 %}
{% block header %}
  <h2>Добавить новый проект:</h2>
{% endblock header %}
{% block content %}
  <form action="{% url 'projects:new_task' %}" method='post'
      class="form">
{% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
      <button name="submit" class="btn btn-primary">Добавить проект</button>
    {% endbuttons %}
</form>
{% endblock content %}

projects/templates/projects/proof.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proof</title>
</head>
<body>
    <h2>Спасибо за регистрацию! Дождитесь подтверждения вашего аккаунта от администратора.</h2>
</body>
</html>

projects/templates/projects/read_task.html
{% extends "projects/base.html" %}
{% block content %}
<h2><b> Проект: </b> {{ task.text }}</h2>
<form action="{% url 'projects:read_task' task.id %}" method='get'>
    {% csrf_token %}



   <h3><b>Название проекта:</b> {{task.text}}</h3>
  <table cellpadding="15" cellspacing="15" border="0" align="left" >
    <tr>
      <td width="500">



        <h4><b>Уникальный номер проекта:</b> {{task.name1}}</h4>
        <p><b>Фонд</b> {{task.fond}}</p>
        <p><b>Основание для проведения проекта</b> {{task.foundation}}</p>
        <p><b>Дата начала проекта:</b> {{task.start}}</p>
        <p><b>Дата окончания проекта:</b>{{task.finish}}</p>
        <p><b>Тип проекта (НИР, ОКР, ...)</b> {{task.pr_type}}</p>
      </td>
      <td width="500">
        <h4><b>Полная сумма проекта:</b> {{task.pr_cost}}</h4>
        <p><b>Организация:</b> {{task.pr_org}}</p>
        <p><b>Соисполнители</b> {{task.pr_also}}</p>
        <p><b>Примечания</b> {{task.pr_notes}}</p>
        <p><b>Комментарии</b> {{task.pr_comments}}</p>
      </td>
    </tr>
  </table>



  </form>


{% endblock content %}

projects/templates/projects/task.html
{% extends 'projects/base.html' %}

{% block header %}
  <h2>{{ task.text }}</h2>
<h4><a href="{% url 'projects:read_task' task.id %}">Подробная информация</a> </h4>
{% endblock header %}
{% block content %}
<h2>Руководители</h2>

 <table cellpadding="15" cellspacing="15" border="0" align="center" >
    <tr>
      <td width="600">
{% for emp in task.emp_set.all %}
          {% if emp.leader %}
<h2>
 <a href="{% url 'workers:emp' emp.id %}">{{ emp.text }}  {{emp.name1}}</a>
</h2>
          {% endif %}
{% endfor %}
      </td>
      <td width="600">
       {% for emp in task.emp_set.all %}
          {% if emp.leader %}
<form action="{% url 'projects:rem_emps' emp.id task.id %}" method="post" class="form">
        {% csrf_token %}
  <h2></h2>
      <button name="submit">Удалить из проекта</button>

</form>
          {% endif %}
        {% endfor %}
      </td>
        <td width="600">
       {% for emp in task.emp_set.all %}
            {% if emp.leader %}
<form action="{% url 'projects:make_leader' emp.id task.id %}" method="post" class="form">
        {% csrf_token %}
  <h2></h2>
      <button name="submit">Убрать руководство</button>

</form>
            {% endif %}
        {% endfor %}
      </td>
    </tr>
 </table>

<h2>Исполнители</h2>

 <table cellpadding="15" cellspacing="15" border="0" align="center" >
    <tr>
      <td width="600">
{% for emp in task.emp_set.all %}
          {% if not emp.leader %}
<h2>
<<<<<<< HEAD
 <a href="{% url 'workers:emp' emp.id %}">{{ emp.text }} {{emp.name1}}</a>
=======
 <a href="{% url 'workers:emp' emp.id %}">{{ emp.text }}  {{emp.name1}}</a>
>>>>>>> c5b5bdb6d6299434d21280762647d098e50c7ab5
</h2>
          {% endif %}
{% endfor %}
      </td>
      <td width="600">
       {% for emp in task.emp_set.all %}
          {% if not emp.leader %}
<form action="{% url 'projects:rem_emps' emp.id task.id %}" method="post" class="form">
        {% csrf_token %}
  <h2></h2>
      <button name="submit">Удалить из проекта</button>

</form>
          {% endif %}
        {% endfor %}
      </td>
        <td width="600">
       {% for emp in task.emp_set.all %}
            {% if not emp.leader %}
<form action="{% url 'projects:make_leader' emp.id task.id %}" method="post" class="form">
        {% csrf_token %}
  <h2></h2>
      <button name="submit">Сделать руководителем</button>

</form>
            {% endif %}
        {% endfor %}
      </td>
    </tr>
 </table>
<h3><a href="{% url 'projects:add_emps' task.id %}">Добавить исполнителя</a></h3>


<p></p>
<p></p>
<!-- Сюда можно включить шаблон с результатами через include
      Или выделить для него отдельный блок -->

{% endblock content %}

projects/templates/projects/tasks.html
{% extends "projects/base.html" %}
{% block header %}
  <h1>Проекты</h1>
{% endblock header %}
{% block content %}
    <form method="GET" action="{% url 'projects:search_task' %}" >
    <input type="text" name="q" placeholder="Поиск" value="{{ request.GET.q }}" />
    <button type="submit">Поиск</button>
</form>
<ul>
{% for task in tasks %}
<li>
        <h3>
          <a href="{% url 'projects:task' task.id %}">{{ task.text }}</a>
        </h3>
</li>
{% empty %}


{% endfor %}
</ul>
<h3><a href="{% url 'projects:new_task' %}">Добавить новый проект </a></h3>
{% endblock content %}